import argparse
import hashlib
import html
import json
from datetime import datetime, timezone
from pathlib import Path


def esc(value):
    return html.escape('' if value is None else str(value))


def sha256_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser(description='Generate an EchoCert HTML audit report')
    parser.add_argument('receipt', help='Path to receipt JSON')
    parser.add_argument('--out', default='reports/audit_report.html', help='Output HTML report path')
    args = parser.parse_args()

    receipt_path = Path(args.receipt)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if not receipt_path.exists():
        raise SystemExit(f'Receipt not found: {receipt_path}')

    data = json.loads(receipt_path.read_text(encoding='utf-8'))
    prompt = data.get('prompt', '')
    output = data.get('output', '')
    metadata = data.get('metadata', {})

    actual_hash = sha256_file(receipt_path)
    seal_path = receipt_path.with_name(receipt_path.name + '.sha256')
    if seal_path.exists():
        expected_hash = seal_path.read_text(encoding='utf-8').strip()
        status = 'VERIFIED' if actual_hash == expected_hash else 'FAILED'
    else:
        expected_hash = 'No .sha256 file found'
        status = 'UNSEALED'

    rows = ''
    for key, value in sorted(metadata.items()):
        rows += f'<tr><th>{esc(key)}</th><td>{esc(value)}</td></tr>\n'

    report = f'''<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>EchoCert Audit Report</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.45; }}
h1 {{ border-bottom: 3px solid #111; padding-bottom: 10px; }}
h2 {{ border-bottom: 1px solid #ccc; padding-bottom: 6px; margin-top: 28px; }}
.badge {{ display: inline-block; padding: 6px 10px; border: 1px solid #111; font-weight: bold; }}
pre {{ white-space: pre-wrap; background: #f6f6f6; border: 1px solid #ddd; padding: 14px; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top; }}
th {{ width: 220px; background: #f3f3f3; }}
code {{ word-break: break-all; }}
.small {{ color: #555; font-size: 0.9em; }}
</style>
</head>
<body>
<h1>EchoCert Audit Report</h1>
<p><strong>Status:</strong> <span class="badge">{esc(status)}</span></p>
<p><strong>Generated UTC:</strong> {esc(datetime.now(timezone.utc).isoformat())}</p>
<p><strong>Receipt file:</strong> {esc(receipt_path)}</p>

<h2>Integrity Check</h2>
<p><strong>Actual SHA-256:</strong><br><code>{esc(actual_hash)}</code></p>
<p><strong>Expected SHA-256:</strong><br><code>{esc(expected_hash)}</code></p>

<h2>Prompt</h2>
<pre>{esc(prompt)}</pre>

<h2>AI Output</h2>
<pre>{esc(output)}</pre>

<h2>Metadata</h2>
<table>{rows}</table>

<h2>Important Limits</h2>
<p>This report shows what was recorded and whether the receipt still matches its SHA-256 seal. It does not prove that the AI output is true, lawful, safe, or complete. It is an evidence organisation and integrity report only.</p>

<p class="small">Generated by EchoCert. Open this file in a browser and use Print / Save as PDF to create a PDF copy.</p>
</body>
</html>'''

    out_path.write_text(report, encoding='utf-8')
    print(f'Report written: {out_path}')


if __name__ == '__main__':
    main()
